name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action build your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
branding:
  color: red
  icon: wifi
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
    required: false
  esp_idf_version:
    description: 'Version of ESP-IDF docker image to use'
    default: 'latest'
    required: false

runs:
  using: "composite"
  steps:
    - run: docker run -t -v "${GITHUB_WORKSPACE}/${{ inputs.path }}:/app" -w=/app espressif/idf:${{ inputs.esp_idf_version }} idf.py build
      shell: bash
